/* global console */
// Include any images needed in templates here.
// This file is only required by core, and so has a long cache time.

define([
    'svg-inline!svgs/icon/comment-16.svg',
    'svg-inline!svgs/icon/marque-36.svg',
    'svg-inline!svgs/icon/marque-54.svg',
    'svg-inline!svgs/icon/market-down.svg',
    'svg-inline!svgs/icon/market-up.svg',
    'svg-inline!svgs/icon/market-same.svg',
    'svg-inline!svgs/icon/arrow.svg',
    'svg-inline!svgs/icon/arrow-down.svg',
    'svg-inline!svgs/icon/cross.svg',
    'svg-inline!svgs/icon/quote.svg',
    'svg-inline!svgs/logo/logo-guardian.svg',
    'svg-inline!svgs/commercial/logo-soulmates.svg',
    'svg-inline!svgs/commercial/soulmates-join.svg',
    'svg-inline!svgs/commercial/logo-jobs.svg',
    'svg-inline!svgs/commercial/logo-masterclasses.svg',
    'svg-inline!svgs/commercial/logo-masterclasses-horizontal.svg',
    'svg-inline!svgs/commercial/logo-membership-horizontal.svg',
    'svg-inline!svgs/commercial/logo-jobs-horizontal.svg',
    'svg-inline!svgs/commercial/logo-bookshop-horizontal.svg',
    'svg-inline!svgs/commercial/icon-clock.svg',
    'svg-inline!svgs/commercial/icon-location.svg',
    'svg-inline!svgs/commercial/icon-basket.svg',
    'svg-inline!svgs/commercial/paid-content.svg',
    'svg-inline!svgs/icon/close-central.svg',
    'svg-inline!svgs/icon/arrow-white-right.svg',
    'svg-inline!svgs/icon/arrow-right.svg',
    'svg-inline!svgs/icon/bookmark.svg',
    'svg-inline!svgs/icon/dropdown-mask.svg',
    'svg-inline!svgs/icon/comment-anchor.svg',
    'svg-inline!svgs/icon/reply.svg',
    'svg-inline!svgs/icon/expand-image.svg',
    'svg-inline!svgs/icon/cursor.svg',
    'svg-inline!svgs/icon/plus.svg',
    'svg-inline!svgs/icon/share.svg',
    'svg-inline!svgs/icon/share-twitter.svg',
    'svg-inline!svgs/icon/share-email.svg',
    'svg-inline!svgs/icon/share-facebook.svg',
    'svg-inline!svgs/icon/share-pinterest.svg',
    'svg-inline!svgs/icon/share-gplus.svg',
    'svg-inline!svgs/icon/external-link.svg',
    'svg-inline!svgs/icon/tick.svg',
    'svg-inline!svgs/icon/notification-off.svg',
    'svg-inline!svgs/icon/notification-on.svg',
    'svg-inline!svgs/logo/glabs-logo-small.svg',
    'svg-inline!svgs/logo/membership-logo.svg',
    'svg-inline!svgs/commercial/logo-membership.svg',
    'svg-inline!svgs/commercial/adblock-coins.svg',
    'svg-inline!svgs/notifications-explainer-desktop.svg',
    'svg-inline!svgs/notifications-explainer-mobile.svg',
    'svg-inline!svgs/commercial/adblock-coins-us.svg',
    'svg-inline!svgs/icon/star.svg',
    'common/views/svg'
], function (
    commentCount16icon,
    marque36icon,
    marque54icon,
    marketDownIcon,
    marketUpIcon,
    marketSameIcon,
    arrowicon,
    arrowdownicon,
    crossIcon,
    quoteIcon,
    logoguardian,
    logosoulmates,
    logosoulmatesjoin,
    logojobs,
    logomasterclasses,
    logomasterclasseshorizontal,
    logomembershiphorizontal,
    logojobshorizontal,
    logobookshophorizontal,
    iconClock,
    iconLocation,
    iconBasket,
    paidContent,
    closeCentralIcon,
    arrowWhiteRight,
    arrowRight,
    bookmark,
    dropdownMask,
    commentAnchor,
    reply,
    expandImage,
    cursor,
    plus,
    share,
    shareTwitter,
    shareEmail,
    shareFacebook,
    sharePinterest,
    shareGPlus,
    externalLink,
    tick,
    notificationsOff,
    notificationsOn,
    glabsLogoSmall,
    membershipLogoWhite,
    membershipLogo,
    adblockCoins,
    notificationsExplainerDesktop,
    notificationsExplainerMobile,
    adblockCoinsUS,
    star,
    svg
) {
    var svgs = {
        commentCount16icon: commentCount16icon,
        marque36icon: marque36icon,
        marque54icon: marque54icon,
        marketDownIcon: marketDownIcon,
        marketUpIcon: marketUpIcon,
        marketSameIcon: marketSameIcon,
        arrowicon: arrowicon,
        arrowdownicon: arrowdownicon,
        crossIcon: crossIcon,
        quoteIcon: quoteIcon,
        logoguardian: logoguardian,
        logosoulmates: logosoulmates,
        logosoulmatesjoin: logosoulmatesjoin,
        logojobs: logojobs,
        logomasterclasses: logomasterclasses,
        logomasterclasseshorizontal: logomasterclasseshorizontal,
        logomembershiphorizontal: logomembershiphorizontal,
        logojobshorizontal: logojobshorizontal,
        logobookshophorizontal: logobookshophorizontal,
        iconClock: iconClock,
        iconLocation: iconLocation,
        iconBasket: iconBasket,
        paidContent: paidContent,
        closeCentralIcon: closeCentralIcon,
        arrowWhiteRight: arrowWhiteRight,
        arrowRight: arrowRight,
        bookmark: bookmark,
        dropdownMask: dropdownMask,
        commentAnchor: commentAnchor,
        reply: reply,
        expandImage: expandImage,
        cursor: cursor,
        plus: plus,
        share: share,
        shareTwitter: shareTwitter,
        shareEmail: shareEmail,
        shareFacebook: shareFacebook,
        sharePinterest: sharePinterest,
        shareGPlus: shareGPlus,
        externalLink: externalLink,
        tick: tick,
        notificationsOff: notificationsOff,
        notificationsOn: notificationsOn,
        glabsLogoSmall: glabsLogoSmall,
        adblockCoinsUk: adblockCoins,
        adblockCoinsUs: adblockCoinsUS,
        logomembership: membershipLogo,
        notificationsExplainerDesktop: notificationsExplainerDesktop,
        notificationsExplainerMobile: notificationsExplainerMobile,
        star: star,
        logomembershipwhite: membershipLogoWhite
    };

    return function (name, classes, title) {
        return svg(svgs[name], classes, title);
    };
});
